export type FlightSeed = {
  code: string;
  aircraft: string;
  origin_code: string;
  origin_city: string;
  destination_code: string;
  destination_city: string;
  departure_time: string;
  arrival_time: string;
  status: string;
  progress: number;
  capacity_tons: number;
  used_tons: number;
};

export const flightSeedData: FlightSeed[] = [
  {
    code: "PT-882",
    aircraft: "Boeing 777-F",
    origin_code: "CGK",
    origin_city: "Jakarta",
    destination_code: "SIN",
    destination_city: "Singapore",
    departure_time: "08:45",
    arrival_time: "10:30",
    status: "ACTIVE",
    progress: 65,
    capacity_tons: 60,
    used_tons: 48,
  },
  {
    code: "PT-914",
    aircraft: "Airbus A330-200F",
    origin_code: "SIN",
    origin_city: "Singapore",
    destination_code: "HKG",
    destination_city: "Hong Kong",
    departure_time: "11:15",
    arrival_time: "15:45",
    status: "DELAY",
    progress: 20,
    capacity_tons: 55,
    used_tons: 42,
  },
  {
    code: "PT-115",
    aircraft: "Boeing 747-8F",
    origin_code: "CGK",
    origin_city: "Jakarta",
    destination_code: "NRT",
    destination_city: "Tokyo",
    departure_time: "13:00",
    arrival_time: "21:15",
    status: "SCHEDULED",
    progress: 0,
    capacity_tons: 70,
    used_tons: 35,
  },
  {
    code: "PT-552",
    aircraft: "Airbus A350-F",
    origin_code: "HKG",
    origin_city: "Hong Kong",
    destination_code: "LHR",
    destination_city: "London",
    departure_time: "16:20",
    arrival_time: "05:10",
    status: "ACTIVE",
    progress: 25,
    capacity_tons: 65,
    used_tons: 51,
  },
  {
    code: "PT-771",
    aircraft: "Boeing 767-F",
    origin_code: "CGK",
    origin_city: "Jakarta",
    destination_code: "DPS",
    destination_city: "Denpasar",
    departure_time: "18:10",
    arrival_time: "20:05",
    status: "ACTIVE",
    progress: 80,
    capacity_tons: 45,
    used_tons: 38,
  },
  {
    code: "PT-330",
    aircraft: "Airbus A321P2F",
    origin_code: "SUB",
    origin_city: "Surabaya",
    destination_code: "KNO",
    destination_city: "Medan",
    departure_time: "09:30",
    arrival_time: "12:10",
    status: "SCHEDULED",
    progress: 0,
    capacity_tons: 32,
    used_tons: 18,
  },
  {
    code: "PT-999",
    aircraft: "Boeing 737-800BCF",
    origin_code: "DPS",
    origin_city: "Denpasar",
    destination_code: "CGK",
    destination_city: "Jakarta",
    departure_time: "06:15",
    arrival_time: "07:45",
    status: "ACTIVE",
    progress: 55,
    capacity_tons: 28,
    used_tons: 22,
  },
  {
    code: "PT-202",
    aircraft: "Airbus A320P2F",
    origin_code: "KNO",
    origin_city: "Medan",
    destination_code: "BPN",
    destination_city: "Balikpapan",
    departure_time: "14:00",
    arrival_time: "17:20",
    status: "ACTIVE",
    progress: 40,
    capacity_tons: 30,
    used_tons: 19,
  },
  {
    code: "PT-404",
    aircraft: "Boeing 757-200PCF",
    origin_code: "BPN",
    origin_city: "Balikpapan",
    destination_code: "SUB",
    destination_city: "Surabaya",
    departure_time: "10:45",
    arrival_time: "13:30",
    status: "DELAY",
    progress: 15,
    capacity_tons: 38,
    used_tons: 27,
  },
  {
    code: "PT-505",
    aircraft: "Airbus A330-300P2F",
    origin_code: "SIN",
    origin_city: "Singapore",
    destination_code: "DPS",
    destination_city: "Denpasar",
    departure_time: "19:30",
    arrival_time: "22:10",
    status: "ACTIVE",
    progress: 70,
    capacity_tons: 52,
    used_tons: 44,
  },
];